In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

In [ ]:
data = np.array(
    [
        [19, 18, np.NaN, 26],
        [85, 53, 76, 45],
        [83, 97, 1, np.NaN],
        [73, 28, 38, 37],
        [87, np.NaN, 86, 66],
        [23, 28, 11, 10],
    ]
)
print("Original Data: ")
print(data)
print(np.isnan(data).any())  # Check if there is any NaN value in that array
imp = SimpleImputer(
    strategy="median"
)  # Specifies that missing values should be replaced with the median value of each column

# fit: Calculates the median of each column (ignoring NaN values)
# transform: Replaces all NaN values with their respective column medians
# col1: [18, 53, 97, 28, NaN, 28]
# ascending order: [18, 28, 28, 53, 97]
# median is 28 and that would replace NaN value in col1
data_new = imp.fit_transform(data)
print("New Data:")
print(data_new)

Original Data: 
[[19. 18. nan 26.]
 [85. 53. 76. 45.]
 [83. 97.  1. nan]
 [73. 28. 38. 37.]
 [87. nan 86. 66.]
 [23. 28. 11. 10.]]
True
New Data:
[[19. 18. 38. 26.]
 [85. 53. 76. 45.]
 [83. 97.  1. 37.]
 [73. 28. 38. 37.]
 [87. 28. 86. 66.]
 [23. 28. 11. 10.]]
