In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array([1,2,3.14], dtype=int)

array([1, 2, 3])

In [5]:
np.array([1,2,3.14], dtype=float)

array([1.  , 2.  , 3.14])

In [6]:
np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
np.random.rand(2,3)

array([[0.64229871, 0.45945891, 0.89108801],
       [0.38200484, 0.87502305, 0.15811155]])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [15]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [16]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [20]:
np.linspace(10, 30, 6)

array([10., 14., 18., 22., 26., 30.])

In [24]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

print(m.size)
print(m.shape)
print(m.ndim)

6
(2, 3)
2


In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
reshape_a = a.reshape(2,3)
print(reshape_a)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
try:
    reshape_a = a.reshape(2, 5)
except ValueError as ex:
    print(f"ValueError: {ex}")

ValueError: cannot reshape array of size 6 into shape (2,5)


In [28]:
# In NumPy, when we use -1 in the reshape method, it acts as a placeholder that tells NumPy to automatically calculate the appropriate size for that dimension based on the size of the array and the other specified dimensions.
a = np.arange(1,7,1)

# We want 3 rows, determine columns
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
# we want 3 cols, determine rows
a.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
m = np.arange(1,7,1).reshape(2,3)
print(m)
transpose_m = m.transpose()
print(transpose_m)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [39]:
array1 = np.arange(1,7,1).reshape(3,2)
flatten_array1 = array1.flatten()
print(array1)
print(flatten_array1, type(flatten_array1))
print('-' * 20)

# flatten returns a deep copy
flatten_array1[0] = 10 # updates value in flatten_array1 but not in array1
print(array1)
print(flatten_array1)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6] <class 'numpy.ndarray'>
--------------------
[[1 2]
 [3 4]
 [5 6]]
[10  2  3  4  5  6]


In [38]:
array2 = np.arange(1, 7, 1).reshape(3, 2)
ravel_array2 = array2.ravel()
print(array2)
print(ravel_array2, type(ravel_array2))
print('-' * 20)

# ravel returns a shallow copy
ravel_array2[0] = 10 # updates value in both flatten_array2 and array2
print(array2)
print(ravel_array2)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6] <class 'numpy.ndarray'>
--------------------
[[10  2]
 [ 3  4]
 [ 5  6]]
[10  2  3  4  5  6]


In [50]:
a = np.arange(1,7,1)
print(a, a.shape)
expand_a = np.expand_dims(a, axis=0) # converts shape from (6,) to (1, 6) i.e, converts 1-D to 2-D along x-axis
print(expand_a.shape)
print(expand_a)

[1 2 3 4 5 6] (6,)
(1, 6)
[[1 2 3 4 5 6]]


In [49]:
a = np.arange(1,7,1)
print(a, a.shape)
expand_a = np.expand_dims(a, axis=1) # converts shape from (6,) to (6, 1) i.e, converts 1-D to 2-D along y-axis
print(expand_a.shape)
print(expand_a)

[1 2 3 4 5 6] (6,)
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [45]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

expand_m = np.expand_dims(m, axis=0) # Converts 2-D array of shape (2, 3) to 3-D array of shape(1, 2, 3)
print(expand_m.shape)
print(expand_m)

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [51]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

expand_m = np.expand_dims(m, axis=1) # Converts 2-D array of shape (2, 3) to 3-D array of shape(2, 1, 3)
print(expand_m.shape)
print(expand_m)

(2, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]


In [55]:
m = np.array(
    [
        [
            [1,2,3],
            [4,5,6]
        ]
    ]
)

print(m, m.shape)
try:
    np.squeeze(m, axis=2) # cannot select an axis to squeeze out which has size not equal to one
except ValueError as ex:
    print(f"ValueError: {ex}")

squeeze_m = np.squeeze(m, axis=0)
print(squeeze_m, squeeze_m.shape)

[[[1 2 3]
  [4 5 6]]] (1, 2, 3)
ValueError: cannot select an axis to squeeze out which has size not equal to one
[[1 2 3]
 [4 5 6]] (2, 3)


In [59]:
a = np.arange(1,7,1)
print(f'a = {a}')
print(a[1:5])
print(a[1:5:2])

a = [1 2 3 4 5 6]
[2 3 4 5]
[2 4]


In [60]:
m = np.arange(1,7,1).reshape(2,3)
print(m)
print(m[0,0])
print(m[1,0])
print(m[0,2])
print(m[1,2])

[[1 2 3]
 [4 5 6]]
1
4
3
6


In [61]:
m[:,1:2]

array([[2],
       [5]])

In [62]:
m[0:1,:]

array([[1, 2, 3]])

In [63]:
m[0:1]

array([[1, 2, 3]])

In [65]:
m = np.array(
    [
        [
            [10, 20],
            [30, 40],
            [50, 60]
        ],
        [
            [70, 80],
            [90, 100],
            [110, 120]
        ],
        [
            [130, 140],
            [150, 160],
            [170, 180]
        ]
    ]
)
m, m.shape

(array([[[ 10,  20],
         [ 30,  40],
         [ 50,  60]],
 
        [[ 70,  80],
         [ 90, 100],
         [110, 120]],
 
        [[130, 140],
         [150, 160],
         [170, 180]]]),
 (3, 3, 2))

In [66]:
m[0, 0, 1]

np.int64(20)

In [67]:
m[1:,0:2, 0:2]

array([[[ 70,  80],
        [ 90, 100]],

       [[130, 140],
        [150, 160]]])

In [68]:
m = np.arange(1, 7, 1).reshape(2, 3)
print(m, m.shape)
flip_m = np.flip(m, axis=0)
print(flip_m,flip_m.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[4 5 6]
 [1 2 3]] (2, 3)


In [69]:
flip_m = np.flip(m, axis=1)
print(flip_m, flip_m.shape)

[[3 2 1]
 [6 5 4]] (2, 3)


In [75]:
a = np.arange(1,4)
b = np.arange(4,7)
a1 = np.arange(10,50,10).reshape(2,2)
b1 = np.arange(50, 90, 10).reshape(2,2)

v_stack = np.vstack((a, b)) # no. of columns should be same
print(v_stack)
h_stack = np.hstack((a1,b1)) # no. of rows should be same
print(h_stack)
d_stack = np.dstack((a1, b1))
print(d_stack)

x_concat = np.concatenate((a1, b1), axis=0) # same as vertical stack
print(x_concat)

y_concat = np.concatenate((a1, b1), axis=1) # same as horizontal stack
print(y_concat)

[[1 2 3]
 [4 5 6]]
[[10 20 50 60]
 [30 40 70 80]]
[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20 50 60]
 [30 40 70 80]]


In [76]:
a = np.arange(10, 100, 20)
b = np.array(
    [
        [3],
        [3]
    ]
)

print(a, a.shape)
print(b, b.shape)

[10 30 50 70 90] (5,)
[[3]
 [3]] (2, 1)


In [82]:
print(a + b)
print(a * 2)
print(a + 3)
print(a // 2)
print(a % 3)
print(a / 2)

[[13 33 53 73 93]
 [13 33 53 73 93]]
[ 20  60 100 140 180]
[13 33 53 73 93]
[ 5 15 25 35 45]
[1 0 2 1 0]
[ 5. 15. 25. 35. 45.]


In [94]:
m = np.arange(1,7,1).reshape(2, 3)
print(m)
print(np.mean(m))
print(np.mean(m, axis=0))
print(np.mean(m, axis=1))
print(np.mean(m))
print(np.median(m))
print(np.std(m))
print(m.sum())
print(m.sum(axis=0))

[[1 2 3]
 [4 5 6]]
3.5
[2.5 3.5 4.5]
[2. 5.]
3.5
3.5
1.707825127659933
21
[5 7 9]


In [95]:
a = np.array([10, 17, 5, 2, 22, 28, 13])
np.sort(a)

array([ 2,  5, 10, 13, 17, 22, 28])

In [97]:
asc_sort_a = np.sort(a)
desc_sort_a = np.sort(a)[::-1]
print(asc_sort_a)
print(desc_sort_a)

[ 2  5 10 13 17 22 28]
[28 22 17 13 10  5  2]
